"""Render the client-facing rescue report (console + RESCUE_REPORT.md)."""

from __future__ import annotations

import sys
from pathlib import Path

from .clean import RescueLog, rescue


def report_markdown(log: RescueLog) -> str:
    lines = [
        "# 🧹 Rescue Report",
        "",
        "What the cleaning pipeline found and fixed in `data/messy_sales.csv`.",
        "Every number below is counted by the pipeline itself — nothing is estimated.",
        "",
        "## Headline",
        "",
        f"| | |",
        f"|---|---|",
        f"| Rows in | {log.rows_in:,} |",
        f"| Rows out (clean) | {log.rows_out:,} |",
        f"| Rows quarantined for human review | {log.rows_quarantined:,} |",
        f"| Duplicate rows removed | {log.duplicate_rows_removed:,} |",
        f"| **Revenue visible to a naive sum** | **${log.naive_revenue:,.2f}** |",
        f"| **Revenue after rescue** | **${log.clean_revenue:,.2f}** |",
        f"| **Revenue recovered by cleaning** | **${log.revenue_recovered:,.2f}** |",
        "",
        "*\"Naive sum\" = what you get if you total the spreadsheet as-is: every",
        "price stored as text ($1,234.56, 1,234.56 USD, …) is invisible to it.*",
        "",
        "## Repairs, itemized",
        "",
        f"- **{log.dates_normalized:,} dates normalized** from 5+ formats",
        f"  ({log.dates_excel_serial:,} were raw Excel serial numbers like `46045`)",
        f"- **{log.money_values_parsed:,} prices parsed** out of currency text",
        f"- **{log.decimal_shifts_fixed:,} decimal-shift typos fixed** (a $42 item entered as $4,200)",
        f"- **{log.customer_variants_merged:,} customer name variants merged** "
        f"({log.customers_before:,} raw spellings → {log.customers_after:,} real customers)",
        f"- **{log.categories_fixed:,} category labels repaired** (case, typos, aliases)",
        f"- **{log.regions_normalized:,} regions standardized** (\"Virginia\", \"va \" → VA)",
        f"- **{log.order_ids_relabeled:,} order IDs relabeled** (`ord 12345` → `ORD-12345`)",
        f"- **{log.cells_missing_standardized:,} fake-missing cells standardized** "
        "(\"N/A\", \"NULL\", \"-\" → truly blank)",
        f"- **{log.cells_whitespace_trimmed:,} cells de-whitespaced**",
        "",
        "## Quarantined rows (never silently guessed)",
        "",
        "Anything ambiguous goes to `data/quarantine.csv` with a reason, so a",
        "human makes the call — not the script:",
        "",
    ]
    for reason, n in sorted(log.quarantine_reasons.items(), key=lambda kv: -kv[1]):
        lines.append(f"- {n:,} × {reason}")
    lines += [
        "",
        "---",
        "*Generated by the [Messy Spreadsheet Rescue](https://github.com/Nspiroff/messy-spreadsheet-rescue) pipeline.*",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    root = Path(__file__).resolve().parents[1]
    clean_df, quarantined, log = rescue(root / "data" / "messy_sales.csv", out_dir=root / "data")
    md = report_markdown(log)
    (root / "RESCUE_REPORT.md").write_text(md, encoding="utf-8")
    print(md)
    print(f"clean rows -> data/clean_sales.csv ({len(clean_df):,})")
    print(f"quarantine -> data/quarantine.csv ({len(quarantined):,})")


if __name__ == "__main__":
    main()
